<?xml version="1.0" encoding="utf-8"?><Database Name="Multikino" Class="MultikinoLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Multikino;Integrated Security=True" SettingsObjectName="IPR_kasa.Properties.Settings" SettingsPropertyName="MultikinoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Movies" Member="Movies">
    <Type Name="Movies">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="link_filmweb" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Movies_Seance" Member="Seance" ThisKey="id" OtherKey="id_movie" Type="Seance" />
    </Type>
  </Table>
  <Table Name="dbo.Seance" Member="Seance">
    <Type Name="Seance">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="id_movie" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Movies_Seance" Member="Movies" ThisKey="id_movie" OtherKey="id" Type="Movies" IsForeignKey="true" />
    </Type>
  </Table>
</Database>